import pandas as pd 

#engineered features to drop
ef_columns = ['edjefe','edjefa','SQBescolari','SQBage','SQBhogar_total','SQBedjefe', 'SQBhogar_nin',
             'SQBovercrowding', 'SQBdependency', 'SQBmeaned', 'agesq']
#spanish to english dict
col_dict = {'Id': 'id',
            'v2a1': 'rent_payment',
            'hacdor': 'overcrowding_by_bedrooms',
            'rooms': 'rooms',
            'hacapo':'overcrowding_by_rooms',
            'v14a': 'bathroom',
            'refrig': 'refrigerator',
            'v18q': 'tablet',
            'v18q1': 'num_tablets', 
            'r4h1': 'males_under_12',
            'r4h2': 'males_over_12',
            'r4h3': 'num_males',
            'r4m1': 'females_under_12',
            'r4m2': 'females_over_12',
            'r4m3': 'num_females',
            'r4t1': 'persons_under_12',
            'r4t2': 'persons_over_12', 
            'r4t3': 'num_persons',
            'tamhog': 'size_household',
            'tamviv': 'number_persons_household',
            'escolari': 'years_school',
            'rez_esc': 'years_behind_school',
            'hhsize': 'household_size',
            'paredblolad': 'block_brick',
            'paredzocalo': 'wood_zinc_absbesto',
            'paredpreb': 'prefabricated_cement',
            'pareddes': 'waste_material',
            'paredmad': 'wood',
            'paredzinc': 'zink',
            'paredfibras': 'natural_fibers',
            'paredother': 'other_wall',
            'pisomoscer': 'tile',
            'pisocemento': 'cement',
            'pisoother': 'other_floor',
            'pisonatur': 'natural_material_floor',
            'pisonotiene': 'none_floor',
            'pisomadera': 'wood_floor',
            'techozinc': 'metal',
            'techoentrepiso': 'fiber_cement',
            'techocane': 'natural_fibers_roof',
            'techootro': 'other_roof',
            'cielorazo': 'ceiling',
            'abastaguadentro': 'inside',  
            'abastaguafuera': 'outside',  
            'abastaguano': 'water_none',
            'public': 'public', 
            'planpri': 'private_plant',
            'noelec': 'none_electricity',
            'coopele': 'cooperative',
            'sanitario1': 'no_toilet', 
            'sanitario2': 'sewer_cesspool', 
            'sanitario3': 'septic_tank',
            'sanitario5': 'letrine',
            'sanitario6': 'other_sewage', 
            'energcocinar1': 'energy_none', 
            'energcocinar2': 'electricity',
            'energcocinar3': 'gas',
            'energcocinar4':'charcoal', 
            'elimbasu1':'tanker truck',
            'elimbasu2': 'hollow_buried',
            'elimbasu3': 'burning',
            'elimbasu4': 'throwing_space', 
            'elimbasu5': 'throwing_water',
            'elimbasu6': 'other_disposal',
            'epared1': 'wall_bad',
            'epared2': 'wall_regular',
            'epared3': 'wall_good',
            'etecho1': 'roof_bad',
            'etecho2': 'roof_regular',
            'etecho3': 'roof_good',
            'eviv1': 'floor_bad',
            'eviv2': 'floor_regular',
            'eviv3': 'floor_good',
            'dis': 'disable_person',
            'male': 'male',
            'female': 'female',
            'estadocivil1': 'under_10',
            'estadocivil2': 'free_or_coupled',
            'estadocivil3': 'married',
            'estadocivil4': 'divorced',
            'estadocivil5': 'separated',
            'estadocivil6': 'widow/er',
            'estadocivil7': 'single',
            'parentesco1': 'household_head',
            'parentesco2': 'spouse/partner',
            'parentesco3': 'son/daughter',
            'parentesco4': 'stepson/daughter',
            'parentesco5': 'son/daughter_inlaw',
            'parentesco6': 'grandson/daughter',
            'parentesco7': 'mother/father',
            'parentesco8': 'father/mother_inlaw',
            'parentesco9': 'brother/sister',
            'parentesco10': 'brother/sister_inlaw',
            'parentesco11': 'other_family_member',
            'parentesco12': 'other_non_family_member',
            'idhogar': 'household_id',
            'hogar_nin': 'num_minors', 
            'hogar_adul': 'num_adults',
            'hogar_mayor': 'num_over_65',
            'hogar_total': 'total_in_household',
            'dependency' : 'calc_dependency', 
            'meaneduc' : 'mean_edu_adults',
            'instlevel1': 'no_education',
            'instlevel2': 'incomplete_primary',
            'instlevel3': 'complete_primary',
            'instlevel4': 'incomplete_secondary',
            'instlevel5': 'complete_secondary',
            'instlevel6': 'incomplete_technical',
            'instlevel7': 'complete_technical',
            'instlevel8': 'undergraduate',
            'instlevel9': 'postgraduate',
            'bedrooms': 'num_bedrooms',
            'overcrowding': 'overcrowding_persons_per_room',
            'tipovivi1': 'own', 
            'tipovivi2': 'own_installments',
            'tipovivi3': 'rented',
            'tipovivi4': 'precarious',
            'tipovivi5': 'other_house',
            'computer': 'computer',
            'television': 'tv',
            'mobilephone': 'mobile_phone',
            'qmobilephone': 'num_mobile_phones',
            'lugar1': 'central',
            'lugar2': 'chorotega',
            'lugar3': 'pacific_central',
            'lugar4': 'brunca',
            'lugar5': 'huetar_atlantic',
            'lugar6': 'huetar_norte',
            'area1': 'urban',
            'area2': 'rural',
            'age': 'age',
            'target': 'target'
           }
#get data, trnaslate, drop enginnered features   
def get_en_df(filename):
    data = pd.read_csv(filename)
    data.drop(ef_columns, axis = 1, inplace = True)
    df = data.rename(columns = col_dict)
    
    return df

